### ISSUE TITLE
Chat command

### ISSUE THREAD

**Issue by littlertom** [Heyter/GoogleSpeech-GM#1]
_note: i have not edited the files._
upon typing one of the chat commands, i am greeted with this console error:

` 
[ERROR] lua/vgui/dcombobox.lua:231: bad argument #1 to 'SetText' (string expected, got nil)
  1. SetText - [C]:-1
   2. SetValue - lua/vgui/dcombobox.lua:231
    3. unknown - addons/googlespeech-gm-master/lua/autorun/client/cl_google.lua:101
     4. func - addons/netlibrary-master/lua/thirdparty/sh_netstream.lua:314
      5. unknown - lua/includes/extensions/net.lua:32
 '

**Comment by Heyter** [comment]
Try new commit.
